[storage]
driver = "overlay"
runroot = "/home/chat/.local/share/containers/run"
graphroot = "/home/chat/.local/share/containers/storage"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
size = ""
remap-uids = "0:100000:65536"
remap-gids = "0:100000:65536"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
